//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Gearset {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resource1 {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Gearset.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Alert {
            get {
                object obj = ResourceManager.GetObject("Alert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] black {
            get {
                object obj = ResourceManager.GetObject("black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cursor {
            get {
                object obj = ResourceManager.GetObject("cursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mark {
            get {
                object obj = ResourceManager.GetObject("mark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tiny {
            get {
                object obj = ResourceManager.GetObject("Tiny", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
